import { Races, Titles, Provinces } from './user-profile-models';

export class UserProfileData {

    static races(): Races[] {
        return [
            { description: 'Black' },
            { description: 'Indian' },
            { description: 'Coloured' },
            { description: 'White' }
        ];
    }
    static titles(): Titles[] {
        return [
            { description: 'Dr' },
            { description: 'Prof' },
            { description: 'Mr' },
            { description: 'Mrs' },
            { description: 'Ms' },
            { description: 'Miss' },
        ];
    }
    static provinces(): Provinces[] {
        return [
            { description: 'Western Cape' },
            { description: 'Eastern Cape' },
            { description: 'Northern Cape' },
            { description: 'North West' },
            { description: 'Free State' },
            { description: 'KwaZulu-Natal' },
            { description: 'Gauteng' },
            { description: 'Limpopo' },
            { description: 'Mpumalanga' },
        ];
    }

    static cities(){
        return {
            EasternCape: [
                { description: 'Alice' },
                { description: 'Butterworth' },
                { description: 'East London' },
                { description: 'Graaff-Reinet' },
                { description: 'Grahamstown' },
                { description: 'King William’s Town' },
                { description: 'Mthatha' },
                { description: 'Port Elizabeth' },
                { description: 'Queenstown' },
                { description: 'Uitenhage' },
                { description: 'Zwelitsha' }
            ],
            FreeState: [
                { description: 'Bethlehem' },
                { description: 'Bloemfontein' },
                { description: 'Jagersfontein' },
                { description: 'Kroonstad' },
                { description: 'Odendaalsrus' },
                { description: 'Parys' },
                { description: 'Phuthaditjhaba' },
                { description: 'Sasolburg' },
                { description: 'Virginia' },
                { description: 'Welkom' }
            ],
            Gauteng: [
                { description: 'Benoni' },
                { description: 'Boksburg' },
                { description: 'Brakpan' },
                { description: 'Carletonville' },
                { description: 'Germiston' },
                { description: 'Johannesburg' },
                { description: 'Krugersdorp' },
                { description: 'Pretoria' },
                { description: 'Randburg' },
                { description: 'Randfontein' },
                { description: 'Roodepoort' },
                { description: 'Soweto' },
                { description: 'Springs' },
                { description: 'Vanderbijlpark' },
                { description: 'Vereeniging' }
            ],
            KwaZuluNatal: [
                { description: 'Durban' },
                { description: 'Empangeni' },
                { description: 'Ladysmith' },
                { description: 'Newcastle' },
                { description: 'Pietermaritzburg' },
                { description: 'Pinetown' },
                { description: 'Ulundi' },
                { description: 'Umlazi' }
            ],
            Limpopo: [
                { description: 'Giyani' },
                { description: 'Lebowakgomo' },
                { description: 'Musina' },
                { description: 'Phalaborwa' },
                { description: 'Polokwane' },
                { description: 'Seshego' },
                { description: 'Sibasa' },
                { description: 'Thabazimbi' }
            ],
            Mpumalanga: [
                { description: 'Emalahleni' },
                { description: 'Nelspruit' },
                { description: 'Secunda' }
            ],
            NorthWest: [
                { description: 'Klerksdorp' },
                { description: 'Mahikeng' },
                { description: 'Mmabatho' },
                { description: 'Potchefstroom' },
                { description: 'Rustenburg' }
            ],
            NorthernCape: [
                { description: 'Kimberley' },
                { description: 'Kuruman' },
                { description: 'Port Nolloth' }
            ],
            WesternCape: [
                { description: 'Bellville' },
                { description: 'Cape Town' },
                { description: 'Constantia' },
                { description: 'George' },
                { description: 'Hopefield' },
                { description: 'Oudtshoorn' },
                { description: 'Paarl' },
                { description: 'Simon’s Town' },
                { description: 'Stellenbosch' },
                { description: 'Swellendam' },
                { description: 'Worcester' }
            ]
        }
    } 

    static noticePeriods(){
        return [
            { description: 'Immediately' },
            { description: '1 Week' },
            { description: '2 Weeks' },
            { description: '1 Month' },
            { description: '2 Months' },
            { description: '3 Months' },
            { description: '4 Months' },
            { description: '5 Months' },
            { description: '6 Months' },
            { description: '7 Months' },
            { description: '8 Months' },
            { description: '9 Months' },
            { description: '10 Months' },
            { description: '11 Months' },
            { description: '12 Months' }
        ]
    }

    static genders() {
        return [    
            {description: 'Male'},
            {description: 'Female'},
            {description: 'Agender'},
            {description: 'Androgyne'},
            {description: 'Androgynous'},
            {description: 'Bigender'},
            {description: 'Cis'},
            {description: 'Cisgender'},
            {description: 'Cis Female'},
            {description: 'Cis Male'},
            {description: 'Cis Man'},
            {description: 'Cis Woman'},
            {description: 'Cisgender Female'},
            {description: 'Cisgender Male'},
            {description: 'Cisgender Man'},
            {description: 'Cisgender Woman'},
            {description: 'Female to Male'},
            {description: 'FTM'},
            {description: 'Gender Fluid'},
            {description: 'Gender Nonconforming'},
            {description: 'Gender Questioning'},
            {description: 'Gender Variant'},
            {description: 'Genderqueer'},
            {description: 'Intersex'},
            {description: 'Male to Female'},
            {description: 'MTF'},
            {description: 'Neither'},
            {description: 'Neutrois'},
            {description: 'Non-binary'},
            {description: 'Other'},
            {description: 'Pangender'},
            {descriptions: 'Trans'},
            {description: 'Trans*'},
            {description: 'Trans Female'},
            {description: 'Trans* Female'},
            {description: 'Trans Male'},
            {description: 'Trans* Male'},
            {description:'Trans Man'},
            {description: 'Trans* Man'},
            {description: 'Trans Person'},
            {description: 'Trans* Person'},
            {description: 'Trans Woman'},
            {description: 'Trans* Woman'},
            {description: 'Transfeminine'},
            {description: 'Transgender'},
            {description: 'Transgender Female'},
            {description: 'Transgender Male'},
            {description: 'Transgender Man'},
            {description: 'Transgender Person'},
            {description: 'Transgender Woman'},
            {description: 'Transmasculine'},
            {description: 'Transsexual'},
            {description: 'Transsexual Female'},
            {description: 'Transsexual Male'},
            {description: 'Transsexual Man'},
            {description: 'Transsexual Person'},
            {description: 'Transsexual Woman'},
            {description: 'Two-Spirit'},
         
        ]
    }

    static levels() {
        return [
            { description: 'Junior' },
            { description: 'Intermediate' },
            { description: 'Senior' }
        ]
    }

    static nationalities() {
        return [
            { description: 'Afghan' },
            { description: 'Albanian' },
            { description: 'Algerian' },
            { description: 'Argentine' },
            { description: 'Argentinian' },
            { description: 'Australian' },
            { description: 'Austrian' },
            { description: 'Bangladeshi' },
            { description: 'Belgian' },
            { description: 'Bolivian' },
            { description: 'Botswanan' },
            { description: 'Brazilian' },
            { description: 'Bulgarian' },
            { description: 'Cambodian' },
            { description: 'Cameroonian' },
            { description: 'Canadian' },
            { description: 'Chilean' },
            { description: 'Chinese' },
            { description: 'Colombian' },
            { description: 'Costa Rican' },
            { description: 'Croatian' },
            { description: 'Cuban' },
            { description: 'Czech' },
            { description: 'Danish' },
            { description: 'Dominican' },
            { description: 'Ecuadorian' },
            { description: 'Egyptian' },
            { description: 'Salvadorian' },
            { description: 'English' },
            { description: 'Estonian' },
            { description: 'Ethiopian' },
            { description: 'Fijian' },
            { description: 'Finnish' },
            { description: 'French' },
            { description: 'German' },
            { description: 'Ghanaian' },
            { description: 'Greek' },
            { description: 'Guatemalan' },
            { description: 'Haitian' },
            { description: 'Honduran' },
            { description: 'Hungarian' },
            { description: 'Icelandic' },
            { description: 'Indian' },
            { description: 'Indonesian' },
            { description: 'Iranian' },
            { description: 'Iraqi' },
            { description: 'Irish' },
            { description: 'Israeli' },
            { description: 'Italian' },
            { description: 'Jamaican' },
            { description: 'Japanese' },
            { description: 'Jordanian' },
            { description: 'Kenyan' },
            { description: 'Kuwaiti' },
            { description: 'Lao' },
            { description: 'Latvian' },
            { description: 'Lebanese' },
            { description: 'Libyan' },
            { description: 'Lithuanian' },
            { description: 'Malagasy' },
            { description: 'Malaysian' },
            { description: 'Malian' },
            { description: 'Maltese' },
            { description: 'Mexican' },
            { description: 'Mongolian' },
            { description: 'Moroccan' },
            { description: 'Mozambican' },
            { description: 'Namibian' },
            { description: 'Nepalese' },
            { description: 'Dutch' },
            { description: 'New Zealander' },
            { description: 'Nicaraguan' },
            { description: 'Nigerian' },
            { description: 'Norwegian' },
            { description: 'Pakistani' },
            { description: 'Panamanian' },
            { description: 'Paraguayan' },
            { description: 'Peruvian' },
            { description: 'Philippine' },
            { description: 'Polish' },
            { description: 'Portuguese' },
            { description: 'Romanian' },
            { description: 'Russian' },
            { description: 'Saudi' },
            { description: 'Scottish' },
            { description: 'Senegalese' },
            { description: 'Serbian' },
            { description: 'Singaporean' },
            { description: 'Slovak' },
            { description: 'South African' },
            { description: 'Korean' },
            { description: 'Spanish' },
            { description: 'Sri Lankan' },
            { description: 'Sudanese' },
            { description: 'Swedish' },
            { description: 'Swiss' },
            { description: 'Syrian' },
            { description: 'Taiwanese' },
            { description: 'Tajikistani' },
            { description: 'Thai' },
            { description: 'Tongan' },
            { description: 'Tunisian' },
            { description: 'Turkish' },
            { description: 'Ukrainian' },
            { description: 'Emirati' },
            { description: 'British' },
            { description: 'American' },
            { description: 'Uruguayan' },
            { description: 'Venezuelan' },
            { description: 'Vietnamese' },
            { description: 'Welsh' },
            { description: 'Zambian' },
            { description: 'Zimbabwean' }
        ]
    }
}
